### ISSUE TITLE
Workflow to deploy to NPM

### ISSUE THREAD

**Issue by pdyraga** [thesis/solidity-contracts#13]
This repository contains code imported by other projects and they could benefit from `@thesis/solidity-contracts` packages published to NPM registry containing `*.sol` files from this repo.

Tagging @michalinacienciala - not a top priority right now but in case you'll have some spare cycles, worth looking at.

**Comment by michalinacienciala** [comment]
@pdyraga, could you add me to the project? I have the workflow ready to push, but don't have privileges.
```
ERROR: Permission to thesis/solidity-contracts.git denied to michalinacienciala.
fatal: Could not read from remote repository.
```

**Comment by mhluongo** [comment]
Added you @michalinacienciala,  you can accept the invite at https://github.com/thesis/
